# Generated by Django 4.2.11 on 2024-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0002_remove_reminder_active_customuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_duration',
            field=models.FloatField(),
        ),
    ]
