# Generated by Django 4.2.11 on 2024-04-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0004_userdata_alter_reminder_user_alter_sleeprecord_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep_tracking_app.userdata'),
        ),
    ]
