# Generated by Django 4.2.11 on 2024-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0005_alter_reminder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepstatistics',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
