# Generated by Django 4.2.11 on 2024-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_tracking_app', '0006_alter_sleepstatistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepstatistics',
            name='sleep_quality',
            field=models.FloatField(),
        ),
    ]
